######################################################################
##
## Filename: ALU_Control.udo
## Created on: Fri Mar 08 3:24:08 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
