######################################################################
##
## Filename: ALU_tb.udo
## Created on: Fri Mar 01 11:54:18 AM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
