######################################################################
##
## Filename: full_adder_32.udo
## Created on: Sun Feb 24 8:05:17 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
