######################################################################
##
## Filename: full_adder.udo
## Created on: Sun Feb 24 6:43:20 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
