######################################################################
##
## Filename: full_adder_tb.vhd.udo
## Created on: Sun Feb 24 6:47:38 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
