######################################################################
##
## Filename: full_adder_tb_vhd.udo
## Created on: Sun Feb 24 6:49:57 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
