######################################################################
##
## Filename: full_adder_32_tb.udo
## Created on: Mon Feb 25 6:49:06 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
