######################################################################
##
## Filename: inverter_32.udo
## Created on: Wed Feb 27 7:42:15 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
