######################################################################
##
## Filename: less_than_32_tb.udo
## Created on: Fri Mar 01 3:15:16 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
