######################################################################
##
## Filename: less_than_32.udo
## Created on: Fri Mar 01 3:13:09 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
