######################################################################
##
## Filename: registers_tb.udo
## Created on: Fri Mar 08 5:49:57 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
