######################################################################
##
## Filename: sign_extender_16to32.udo
## Created on: Thu Feb 28 7:56:24 PM Mountain Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
